### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Preetam2114** [lostintangent/vsls-whiteboard#28]
The Extension is not working properly on Mac after the new vscode update.
It has stopped showing the whiteboard option.
![Screenshot 2020-11-08 at 11 44 53 PM](https://user-images.githubusercontent.com/30361120/98478362-d9985580-221c-11eb-9de1-828e2b84b565.png)

**Comment by lostintangent** [comment]
Thanks for reporting this! Had this been working, and then suddenly stopped when you updated to the latest VS Code version?

**Comment by Preetam2114** [comment]
Yes, It has started behaving weirdly after I updated my vscode to October 2020 Release(1.51). It shows the whiteboard during some of the live share sessions, but most of the time the whiteboard is missing.

**Comment by vilhelmprytz** [comment]
I've never used this extension before but tried to install it today. The "whiteboard" option does not show up under the live share tab. Is this extension supposed to work on Linux? (I'm on Fedora)

**Comment by lostintangent** [comment]
This has now been fixed! Apologies for the delay 🙏
